export const projects = [
  {
    id: "suknai-real-estate",
    title: "Suknai - Luxury Real Estate Platform",
    desc: "A premium real estate platform showcasing luxury properties. Features high-quality visuals, brand integration, and an elegant user interface for property discovery.",
    category: "Web",
    skills: ["React", "Tailwind CSS", "Framer Motion", "UI/UX"],
    img: "/suknai/screencapture-suknai-vercel-app-2026-04-23-19_20_43.png",
    liveUrl: "https://suknai.vercel.app/",
    githubUrl: "https://github.com/ahmed-abdelmottal3/suknai",
  },
  {
    id: "rawy-mobile-app",
    title: "Rawy - Storytelling Mobile App",
    desc: "A premium mobile application designed for storytelling and narrative experiences. Features a clean, user-centric interface with smooth transitions and interactive elements to provide an immersive reading and listening experience.",
    category: "Mobile",
    skills: ["Flutter", "Dart", "Firebase", "UI/UX"],
    img: "/rawy/rawy.png",
    liveUrl: "",
    githubUrl: "https://github.com/Qubexia/rawyapp",
  },

  {
    id: "monlz-ui-ux-design",
    title: "Monlz - Modern UI/UX Design",
    desc: "A comprehensive UI/UX case study for a modern platform. Focused on minimalist aesthetics, user flow optimization, and high-fidelity prototyping to ensure a seamless user journey.",
    category: "UI/UX",
    skills: ["Figma", "Prototyping", "User Research", "Visual Design"],
    img: "/monlz/monlz1.png",
    liveUrl: "",
    githubUrl: "",
  },

  {
    id: "quizium-platform",
    title: "Quizium - Interactive Quiz Platform",
    desc: "A powerful platform for creating and taking interactive quizzes. Features real-time results, subject-based filtering, and a user-friendly examination interface.",
    category: "Web",
    skills: ["React", "Firebase", "Tailwind CSS", "Redux"],
    img: "/quizium/screencapture-quizium-one-vercel-app-2026-04-23-19_07_48.png",
    liveUrl: "https://quizium-one.vercel.app/",
    githubUrl: "https://github.com/Lumix-projects/Quizium",
  },
  {
    id: "clothera-ecommerce",
    title: "Clothera - E-commerce Fashion Store",
    desc: "A full-featured e-commerce platform for fashion and apparel. Includes product browsing, wishlist, shopping cart, and a seamless checkout experience. Built with modern web technologies for high performance and scalability.",
    category: "Web",
    skills: ["Next.js", "Tailwind CSS", "Redux", "Node.js", "MongoDB"],
    img: "/clothera/screencapture-clothera-vercel-app-2026-04-23-18_57_21.png",
    liveUrl: "https://clothera.vercel.app/",
    githubUrl: "https://github.com/ahmed-abdelmottal3/Clothera",
  },

  {
    id: "portfolio-website",
    title: "My First Freelance Project",
    desc: "A modern and responsive personal portfolio website built with React.js and Tailwind CSS. The design highlights projects, skills, and experience with a clean layout and smooth animations to provide an engaging user experience.",
    category: "Web",
    skills: ["React.js", "Tailwind CSS", "Framer Motion"],
    img: "/portfolio.png",
    liveUrl: "https://ahmed-saleh-two.vercel.app/",
    githubUrl: "https://github.com/ahmed-abdelmottal3/my-first-client-project",
  },
];

